### ISSUE TITLE
[doc] "Generic" in a sentence

### ISSUE THREAD

**Issue by rwp0** [exodist/Term-Table#13]
> This module is able to **generic** format rows of data into tables.

https://github.com/exodist/Term-Table/blob/master/lib/Term/Table.pm#L265

What's meant by this sentence?

Is it a spelling issue?

Thanks

**Comment by exodist** [comment]
I think that word simply needs to be removed. I was probably trying to write generate, but then switched to format, and forgot to remove the partial and misspelled word.
