### ISSUE TITLE
Dependency on non-existent Unicode::GCString version

### ISSUE THREAD

**Issue by ppisar** [exodist/Term-Table#2]
Term-Table-0.002 recommends Unicode::GCString 2015.06. But latest available Unicode::GCString is 2013.10 <http://search.cpan.org/~nezumi/Unicode-LineBreak/lib/Unicode/GCString.pod>. Maybe it's a bug Unicode-LineBreak that forgot to bump the version, but still I think other CPAN distribution should not depend on non-existent modules.

**Comment by exodist** [comment]
uhg, that is irritating, thanks.
